
  ******  DRILL DATA LIST  ******

                        Date/Time : Fri Aug 10 15:07:15 2012
                        Host Name : "MONBAZILLAC"
                        Directory : "L:\PROJETS_2012\Covidien\Dossier_5_Cartes\3_5_CAO_CR5000_BR0505\FAB"
                        User Name : monbazillac

                       <DRP> File : "l:\cr5000\feersc\cr5000\bin\Drill.drp"
                         Comments : ""

                   <PNL/PCB> File : "L:\PROJETS_2012\Covidien\Dossier_5_Cartes\3_5_CAO_CR5000_BR0505\cbr0505-03.pcb"
                  <MRL/MRDB> File : "l:\cr5000\feersc\cr5000\libfee\fee.mrdb"
                    Drill Machine : "EXCELLON"

                  Extended Format : Excellon
                   Character Code : ASCII
                    Record Format : Full Storage
                    Record Length : 512
                     NC Data Unit : Inch
                Coordinate Format : 00V0000
                       Round Unit : 0.00010
        Coordinate Representation : Absolute
                 Omit Coordinates : Off
                    Zero Suppress : Trailing Zero Suppress
 Coordinates during Tool Exchange : Clear
                         EOB Code : LF
                         EOR Code : SPACE
                         ETB Code : SPACE
                         PAD Code : SPACE

                       <DRD> File : ".\per1.drd"
                       <DRL> File : ".\per1.drl"

                        List Unit : Millimeters

                            Layer : Only through holes
                Plating attribute : Off
                           Figure : Round/Slot
             Way to output oblong : Alternate (Movement rate:0.50000 Odd number:Off)
             Way to output square : ----------

                           Origin : (   0.00000,   0.00000)
                           Mirror : OFF
                         Rotation : (   0)
                            Scale : (   1.00000)
                           Offset : (   0.00000,   0.00000)

                        Data Area : (   0.00000,   0.00000)-(   0.00000,   0.00000)
